# Python build file

universe = vanilla
log = log/CNN_$(Process).log
error  = err/CNN_$(Process).err
output = out/CNN_$(Process).out

executable = CNN.sh
arguments = $(Process)

transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/python38.tar.gz, /staging/groups/STAT605_team1/dataset.tgz, /staging/groups/STAT605_team1/build/packages.tar.gz, CNN.py, randomSearchCNN.csv

request_cpus = 1
request_memory = 3GB
request_disk = 3GB

queue 1000
